version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: Raw dataset schema
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: Sales table
        columns:
          - name: orders_id
            description: Identifier for orders
          - name: pdt_id
            description: Identifier for products
          - name: date_date
            description: Date of the sale
          - name: revenue
            description: Revenue from the sale
          - name: quantity
            description: Quantity sold
      - name: product
        identifier: raw_gz_product
        description: Products table
        columns:
          - name: products_id
            description: Identifier for products
          - name: purchse_price
            description: Purchase price of the product
      - name: ship
        identifier: raw_gz_ship
        description: Shipping table
        columns:
          - name: orders_id
            description: Identifier for orders
          - name: shipping_fee
            description: Shipping fee
          - name: logCost
            description: Logistics cost
          - name: ship_cost
            description: Shipping cost
      - name: adwords
        identifier: raw_gz_adwords
        description: Adwords table
        columns:
          - name: date_date
            description: Date
          - name: paid_source
            description: Paid source
          - name: campaign_key
            description: Campaign key
          - name: camPGN_name
            description: Campaign name
          - name: ads_cost
            description: Ads cost
          - name: impression
            description: Impression count
          - name: click
            description: Click count
      - name: bing
        identifier: raw_gz_bing
        description: Bing table
        columns:
          - name: date_date
            description: Date
          - name: paid_source
            description: Paid source
          - name: campaign_key
            description: Campaign key
          - name: camPGN_name
            description: Campaign name
          - name: ads_cost
            description: Ads cost
          - name: impression
            description: Impression count
          - name: click
            description: Click count
      - name: criteo
        identifier: raw_gz_criteo
        description: Criteo table
        columns:
          - name: date_date
            description: Date
          - name: paid_source
            description: Paid source
          - name: campaign_key
            description: Campaign key
          - name: camPGN_name
            description: Campaign name
          - name: ads_cost
            description: Ads cost
          - name: impression
            description: Impression count
          - name: click
            description: Click count
      - name: facebook
        identifier: raw_gz_facebook
        description: Facebook table
        columns:
          - name: date_date
            description: Date
          - name: paid_source
            description: Paid source
          - name: campaign_key
            description: Campaign key
          - name: camPGN_name
            description: Campaign name
          - name: ads_cost
            description: Ads cost
          - name: impression
            description: Impression count
          - name: click
            description: Click count

models:
  - name: int_sales_margin
    description: "Intermediate model to calculate sales margin"
    columns:
      - name: orders_id
        description: "Primary key for orders"
      - name: products_id
        description: "Foreign key for products"
      - name: date_date
        description: "Date of the order"
      - name: quantity
        description: "Quantity of products ordered"
      - name: revenue
        description: "Revenue generated from the order"
      - name: purchase_cost
        description: "Purchase cost for the products in the order"
      - name: margin
        description: "Margin calculated as revenue minus purchase cost"

  - name: int_campaigns
    description: "Unified model for paid sources"
    columns:
      - name: date_date
        description: "Date"
      - name: paid_source
        description: "Paid source"
      - name: campaign_key
        description: "Campaign key"
      - name: campaign_name
        description: "Campaign name"
      - name: ads_cost
        description: "Ads cost"
      - name: impression
        description: "Impression count"
      - name: click
        description: "Click count"

  - name: int_campaigns_day
    description: "Aggregated campaigns data by day"
    columns:
      - name: date_date
        description: "Date"
      - name: paid_source
        description: "Paid source"
      - name: nb_campaigns
        description: "Number of unique campaigns"
      - name: ads_cost
        description: "Total ads cost"
      - name: impression
        description: "Total impressions"
      - name: click
        description: "Total clicks"

  - name: finance_campaigns_day
    description: "Aggregated finance and campaigns data by day with ads margin"
    columns:
      - name: date_date
        description: "Date"
      - name: paid_source
        description: "Paid source"
      - name: nb_campaigns
        description: "Number of unique campaigns"
      - name: ads_cost
        description: "Total ads cost"
      - name: impression
        description: "Total impressions"
      - name: click
        description: "Total clicks"
      - name: revenue
        description: "Total revenue"
      - name: average_basket
        description: "Average basket value"
      - name: margin
        description: "Margin"
      - name: operational_margin
        description: "Operational Margin"
      - name: ads_margin
        description: "Ads Margin"

  - name: finance_campaigns_month
    description: "Aggregated finance and campaigns data by month with ads margin"
    columns:
      - name: month
        description: "Month"
      - name: paid_source
        description: "Paid source"
      - name: nb_campaigns
        description: "Number of unique campaigns"
      - name: ads_cost
        description: "Total ads cost"
      - name: impression
        description: "Total impressions"
      - name: click
        description: "Total clicks"
      - name: revenue
        description: "Total revenue"
      - name: average_basket
        description: "Average basket value"
      - name: average_basket_bis
        description: "Alternative Average basket value"
      - name: margin
        description: "Margin"
      - name: operational_margin
        description: "Operational Margin"
      - name: purchase_cost
        description: "Purchase Cost"
      - name: shipping_fee
        description: "Shipping Fee"
      - name: logcost
        description: "Logistics Cost"
      - name: ship_cost
        description: "Shipping Cost"
      - name: quantity
        description: "Total Quantity"
      - name: ads_margin
        description: "Ads Margin"
